In [1]:
import pandas as pd
import numpy as np
import pickle
import csv

In [2]:
x = pd.read_csv('train_X_re.csv')
y = pd.read_csv('train_Y_re.csv',header=None)

In [3]:
x

,avg_time_week,project_rate,practice_sets_score,activity,streak,quiz_score,regularity
0,6.0,6.0,324.0,8.0,0.0,114.0,8.82
1,6.0,10.0,326.0,7.0,1.0,112.0,8.99
2,4.0,7.0,338.0,9.0,1.0,122.0,9.38
3,8.0,5.0,334.0,8.0,1.0,114.0,9.04
4,4.0,8.0,299.0,4.0,1.0,101.0,7.82
...,...,...,...,...,...,...,...
370,8.0,9.0,333.0,8.0,1.0,115.0,9.02
371,8.0,7.0,325.0,9.0,0.0,107.0,8.68
372,2.0,6.0,317.0,5.0,1.0,103.0,8.45
373,10.0,8.0,339.0,8.0,1.0,117.0,9.30
374,10.0,9.0,346.0,10.0,1.0,119.0,9.08

In [4]:
y

         0
0    46.10
1    62.10
2    66.67
3    59.81
4    46.86
..     ...
370  62.10
371  56.00
372  52.19
373  65.90
374  70.48

[375 rows x 1 columns]

In [5]:
x.isnull().sum()

avg_time_week          0
project_rate           0
practice_sets_score    0
activity               0
streak                 0
quiz_score             0
regularity             0
dtype: int64

In [6]:
y.isnull().sum()

0    0
dtype: int64

In [7]:
x.head()

,avg_time_week,project_rate,practice_sets_score,activity,streak,quiz_score,regularity
0,6.0,6.0,324.0,8.0,0.0,114.0,8.82
1,6.0,10.0,326.0,7.0,1.0,112.0,8.99
2,4.0,7.0,338.0,9.0,1.0,122.0,9.38
3,8.0,5.0,334.0,8.0,1.0,114.0,9.04
4,4.0,8.0,299.0,4.0,1.0,101.0,7.82

In [8]:
x = x.values
x

array([[  6.  ,   6.  , 324.  , ...,   0.  , 114.  ,   8.82],
       [  6.  ,  10.  , 326.  , ...,   1.  , 112.  ,   8.99],
       [  4.  ,   7.  , 338.  , ...,   1.  , 122.  ,   9.38],
       ...,
       [  2.  ,   6.  , 317.  , ...,   1.  , 103.  ,   8.45],
       [ 10.  ,   8.  , 339.  , ...,   1.  , 117.  ,   9.3 ],
       [ 10.  ,   9.  , 346.  , ...,   1.  , 119.  ,   9.08]])

In [9]:
y = y.values

In [10]:
y

array([[46.1 ],
       [62.1 ],
       [66.67],
       [59.81],
       [46.86],
       [35.43],
       [69.71],
       [51.43],
       [62.1 ],
       [45.33],
       [71.24],
       [46.1 ],
       [65.9 ],
       [52.19],
       [39.24],
       [57.52],
       [69.71],
       [37.71],
       [38.48],
       [46.1 ],
       [44.57],
       [55.24],
       [52.19],
       [62.1 ],
       [69.71],
       [38.48],
       [69.71],
       [55.24],
       [45.33],
       [50.67],
       [52.95],
       [67.43],
       [52.19],
       [30.1 ],
       [52.19],
       [47.62],
       [46.86],
       [52.19],
       [46.1 ],
       [55.24],
       [48.38],
       [62.86],
       [68.95],
       [64.38],
       [44.57],
       [56.76],
       [44.57],
       [55.24],
       [68.19],
       [48.38],
       [46.86],
       [40.76],
       [37.71],
       [54.48],
       [33.9 ],
       [49.14],
       [67.43],
       [58.29],
       [33.14],
       [52.95],
       [61.33],
       [30.86],
       [64.38],
       [44.57],
       [60.57],
       [50.67],
       [39.24],
       [54.48],
       [56.  ],
       [57.52],
       [63.62],
       [43.05],
       [65.14],
       [54.48],
       [49.14],
       [68.19],
       [32.38],
       [54.48],
       [33.9 ],
       [49.14],
       [48.38],
       [53.71],
       [47.62],
       [63.62],
       [39.24],
       [65.9 ],
       [47.62],
       [68.95],
       [58.29],
       [49.9 ],
       [49.14],
       [72.  ],
       [49.14],
       [48.38],
       [57.52],
       [63.62],
       [47.62],
       [33.9 ],
       [68.95],
       [61.33],
       [51.43],
       [67.43],
       [35.43],
       [68.19],
       [58.29],
       [52.19],
       [33.14],
       [52.95],
       [49.9 ],
       [30.1 ],
       [62.1 ],
       [41.52],
       [70.48],
       [59.81],
       [58.29],
       [33.14],
       [34.67],
       [45.33],
       [42.29],
       [52.19],
       [56.  ],
       [68.95],
       [44.57],
       [59.05],
       [65.9 ],
       [33.9 ],
       [63.62],
       [27.05],
       [42.29],
       [53.71],
       [58.29],
       [62.1 ],
       [49.9 ],
       [46.86],
       [39.24],
       [59.05],
       [62.1 ],
       [59.05],
       [34.67],
       [57.52],
       [59.05],
       [68.19],
       [63.62],
       [56.  ],
       [67.43],
       [63.62],
       [62.86],
       [58.29],
       [51.43],
       [48.38],
       [52.95],
       [48.38],
       [36.19],
       [49.9 ],
       [35.43],
       [69.71],
       [71.24],
       [57.52],
       [53.71],
       [51.43],
       [55.24],
       [51.43],
       [45.33],
       [67.43],
       [60.57],
       [56.76],
       [63.62],
       [52.95],
       [59.81],
       [65.14],
       [40.76],
       [56.76],
       [44.57],
       [51.43],
       [52.95],
       [52.19],
       [44.57],
       [53.71],
       [42.29],
       [56.76],
       [41.52],
       [38.48],
       [47.62],
       [47.62],
       [62.1 ],
       [60.57],
       [25.52],
       [65.14],
       [47.62],
       [58.29],
       [54.48],
       [57.52],
       [69.71],
       [31.62],
       [59.05],
       [66.67],
       [49.14],
       [40.76],
       [40.76],
       [38.48],
       [71.24],
       [44.57],
       [37.71],
       [62.86],
       [49.9 ],
       [70.48],
       [40.76],
       [59.05],
       [52.19],
       [70.48],
       [49.9 ],
       [49.9 ],
       [31.62],
       [66.67],
       [26.29],
       [49.14],
       [31.62],
       [42.29],
       [56.  ],
       [59.81],
       [69.71],
       [36.19],
       [58.29],
       [56.  ],
       [62.86],
       [49.14],
       [59.81],
       [55.24],
       [49.14],
       [53.71],
       [41.52],
       [45.33],
       [68.95],
       [64.38],
       [54.48],
       [37.71],
       [63.62],
       [35.43],
       [52.95],
       [72.  ],
       [52.19],
       [68.19],
       [52.19],
       [67.43],
       [24.  ],
       [70.48],
       [45.33],
       [45.33],
       [42.29],
       [67.43],
       [56.  ],
       [66.67],
       [55.24],
       [64.38],
       [55.24],
       [51.43],
       [37.71],
       [45.33],
       [50.67],
       [60.57],
       [65.14],
       [51.43],
       [54.48],
       [46.1 ],
       [62.1 ],
       [52.19],
       [57.52],
       [39.24],
       [59.05],
       [59.81],
       [67.43],
       [53.71],
       [62.1 ],
       [45.33],
       [43.05],
       [33.14],
       [65.9 ],
       [71.24],
       [46.1 ],
       [62.86],
       [53.71],
       [66.67],
       [49.9 ],
       [56.  ],
       [41.52],
       [59.05],
       [53.71],
       [51.43],
       [56.  ],
       [45.33],
       [71.24],
       [47.62],
       [45.33],
       [50.67],
       [41.52],
       [46.86],
       [56.  ],
       [53.71],
       [46.86],
       [40.  ],
       [57.52],
       [56.76],
       [49.9 ],
       [43.05],
       [52.19],
       [46.86],
       [37.71],
       [52.19],
       [66.67],
       [69.71],
       [59.81],
       [44.57],
       [61.33],
       [59.81],
       [41.52],
       [43.05],
       [43.05],
       [36.95],
       [68.95],
       [40.  ],
       [41.52],
       [63.62],
       [52.95],
       [62.86],
       [52.95],
       [57.52],
       [48.38],
       [52.19],
       [43.05],
       [50.67],
       [56.  ],
       [41.52],
       [51.43],
       [56.  ],
       [52.19],
       [60.57],
       [47.62],
       [49.9 ],
       [42.29],
       [69.71],
       [52.95],
       [39.24],
       [57.52],
       [53.71],
       [56.  ],
       [51.43],
       [56.76],
       [66.67],
       [71.24],
       [49.9 ],
       [53.71],
       [54.48],
       [52.19],
       [53.71],
       [65.9 ],
       [52.19],
       [40.76],
       [68.95],
       [71.24],
       [64.38],
       [69.71],
       [30.1 ],
       [72.  ],
       [59.05],
       [33.9 ],
       [35.43],
       [67.43],
       [64.38],
       [59.05],
       [65.9 ],
       [62.1 ],
       [56.  ],
       [52.19],
       [65.9 ],
       [70.48]])

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25,random_state = 0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [13]:
from sklearn.neighbors import KNeighborsRegressor
regressor = KNeighborsRegressor(n_neighb)

In [14]:
regressor.fit(x_train,y_train)

DecisionTreeRegressor()

In [15]:
predictions = regressor.predict(x_test)

In [16]:
predictions,y_test

(array([42.29, 39.24, 59.05, 49.9 , 47.62, 30.86, 67.43, 62.86, 42.29,
        54.48, 58.29, 56.  , 56.  , 43.05, 51.43, 41.52, 35.43, 56.  ,
        49.9 , 27.05, 63.62, 56.  , 39.24, 39.24, 45.33, 46.86, 64.38,
        59.81, 69.71, 54.48, 39.24, 65.9 , 52.19, 45.33, 63.62, 69.71,
        45.33, 69.71, 70.48, 68.95, 42.29, 30.1 , 55.24, 63.62, 59.05,
        62.86, 60.57, 41.52, 44.57, 49.9 , 39.24, 54.48, 44.57, 41.52,
        56.  , 59.05, 56.  , 53.71, 52.95, 65.9 , 59.81, 52.19, 70.48,
        41.52, 70.48, 62.1 , 52.19, 65.9 , 42.29, 53.71, 47.62, 65.9 ,
        62.86, 54.48, 59.05, 65.14, 57.52, 45.33, 65.14, 47.62, 35.43,
        54.48, 52.19, 41.52, 45.33, 42.29, 52.19, 48.38, 43.05, 52.19,
        52.19, 67.43, 39.24, 48.38]),
 array([[44.57],
        [56.  ],
        [61.33],
        [49.9 ],
        [49.9 ],
        [35.43],
        [67.43],
        [63.62],
        [32.38],
        [37.71],
        [57.52],
        [56.76],
        [61.33],
        [36.95],
        [52.19],
        [31.62],
        [33.9 ],
        [59.81],
        [47.62],
        [43.05],
        [62.86],
        [52.19],
        [45.33],
        [38.48],
        [43.05],
        [33.9 ],
        [59.81],
        [64.38],
        [69.71],
        [62.1 ],
        [33.9 ],
        [49.9 ],
        [50.67],
        [56.  ],
        [62.1 ],
        [69.71],
        [45.33],
        [67.43],
        [71.24],
        [69.71],
        [49.14],
        [37.71],
        [59.81],
        [70.48],
        [56.76],
        [57.52],
        [57.52],
        [56.  ],
        [35.43],
        [56.  ],
        [41.52],
        [51.43],
        [35.43],
        [38.48],
        [52.95],
        [62.1 ],
        [49.14],
        [44.57],
        [49.14],
        [68.19],
        [62.86],
        [56.  ],
        [72.  ],
        [40.76],
        [70.48],
        [60.57],
        [49.14],
        [67.43],
        [36.19],
        [45.33],
        [51.43],
        [67.43],
        [62.1 ],
        [53.71],
        [40.  ],
        [57.52],
        [56.  ],
        [53.71],
        [66.67],
        [44.57],
        [39.24],
        [62.1 ],
        [53.71],
        [52.95],
        [33.14],
        [53.71],
        [55.24],
        [52.95],
        [49.9 ],
        [48.38],
        [50.67],
        [65.9 ],
        [33.14],
        [49.14]]))

In [17]:
predictions = predictions.reshape(len(y_test),1)

In [18]:
predictions

array([[42.29],
       [39.24],
       [59.05],
       [49.9 ],
       [47.62],
       [30.86],
       [67.43],
       [62.86],
       [42.29],
       [54.48],
       [58.29],
       [56.  ],
       [56.  ],
       [43.05],
       [51.43],
       [41.52],
       [35.43],
       [56.  ],
       [49.9 ],
       [27.05],
       [63.62],
       [56.  ],
       [39.24],
       [39.24],
       [45.33],
       [46.86],
       [64.38],
       [59.81],
       [69.71],
       [54.48],
       [39.24],
       [65.9 ],
       [52.19],
       [45.33],
       [63.62],
       [69.71],
       [45.33],
       [69.71],
       [70.48],
       [68.95],
       [42.29],
       [30.1 ],
       [55.24],
       [63.62],
       [59.05],
       [62.86],
       [60.57],
       [41.52],
       [44.57],
       [49.9 ],
       [39.24],
       [54.48],
       [44.57],
       [41.52],
       [56.  ],
       [59.05],
       [56.  ],
       [53.71],
       [52.95],
       [65.9 ],
       [59.81],
       [52.19],
       [70.48],
       [41.52],
       [70.48],
       [62.1 ],
       [52.19],
       [65.9 ],
       [42.29],
       [53.71],
       [47.62],
       [65.9 ],
       [62.86],
       [54.48],
       [59.05],
       [65.14],
       [57.52],
       [45.33],
       [65.14],
       [47.62],
       [35.43],
       [54.48],
       [52.19],
       [41.52],
       [45.33],
       [42.29],
       [52.19],
       [48.38],
       [43.05],
       [52.19],
       [52.19],
       [67.43],
       [39.24],
       [48.38]])

In [19]:
mse = np.sum(np.square(y_test - predictions))

In [20]:
mse

3988.3401

In [21]:
pickle.dump(regressor,open('MODEL_FILE.sav','wb'))

ValueError: Number of features of the model must match the input. Model n_features is 7 and input n_features is 1